export const GET_TRANSFER_LIST = 'app/transfer/GET_TRANSFER_LIST';
export const UPDATE_TRANSFER_STATUS = 'app/transfer/UPDATE_TRANSFER_STATUS';

export const ADMIN_STATUS_FROM_TRANSFER_INIT = 0;
export const ADMIN_STATUS_FROM_TRANSFER_RECEIVED = 1;
export const ADMIN_STATUS_FROM_TRANSFER_PROCESSED = 3;
